# Generated by Django 4.1.5 on 2023-01-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ลดราคา'),
        ),
    ]
