# Generated by Django 4.1.5 on 2023-01-16 04:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_discount_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_picture', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ภาพรายละเอียดสินค้า',
                'verbose_name_plural': 'ภาพรายละเอียดสินค้า',
                'db_table': 'pictures',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='คำอธิบายผลิตภัณฑ์'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_thumbnail',
            field=models.URLField(default='no', verbose_name='ภาพขนาดย่อของผลิตภัณฑ์'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='น้ำหนัก'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ราคา'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_pictures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.picture', verbose_name='ภาพรายละเอียดสินค้า'),
        ),
    ]
