# Generated by Django 4.1.5 on 2023-01-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_picture_product_product_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='ProductPicture',
        ),
    ]
